exclude: '^\.git/|.*\.md$|.*\.txt$|.*\.json$|.*\.xml$'
repos:
  # Basic pre-commit checks
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.3.0  # ğŸš€ Use the latest stable version
    hooks:
      - id: trailing-whitespace
        name: 'Trim Trailing Whitespace ğŸ§¹'
      - id: check-merge-conflict
        name: 'Check for Merge Conflicts ğŸš©'
      - id: mixed-line-ending
        name: 'Fix Mixed Line Ending ğŸ”„'
      - id: end-of-file-fixer
        name: 'Fix End of Files ğŸ“'

    # Autoflake - Remove Unused Imports
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.2.1
    hooks:
      - id: autoflake
        name: 'Autoflake (Remove Unused Imports) ğŸ§¹'
        args: [--remove-all-unused-imports, --in-place]

  # Black - Code Formatting
  - repo: https://github.com/psf/black
    rev: 22.3.0  # ğŸ¨ Specify the version of Black you want to use
    hooks:
      - id: black
        name: 'Black (Code Formatter) ğŸ–¤'
        language_version: python3.10  # Specify the Python version

  # isort - Sorting Imports
  - repo: 'https://github.com/PyCQA/isort'
    rev: 5.12.0  # ğŸ“š Use the latest stable version
    hooks:
      - id: isort
        name: 'isort (Imports Sorter) ğŸ—‚'
        args: ['--profile', 'black']

  # MyPy - Static Type Checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910  # ğŸ” Use the latest version of MyPy
    hooks:
      - id: mypy
        name: 'MyPy (Type Checker) ğŸ”'
        additional_dependencies: [types-requests]  # Add additional dependencies if needed
